name: 每日自動更新新聞與圖片

on:
  schedule:
    - cron: '0 0 * * 1-6'  # 每週一到週六，台灣早上 8 點（UTC 0 點）
  workflow_dispatch:

jobs:
  load-settings:
    runs-on: ubuntu-latest
    outputs:
      settings: ${{ steps.load.outputs.settings }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 讀取 settings.txt 為 JSON 字串（提供給下方 Python 用）
        id: load
        run: |
          settings=$(cat settings.txt | python3 -c "import json,sys; print(json.dumps(sys.stdin.read()))")
          echo "settings=$settings" >> $GITHUB_OUTPUT

  build:
    needs: load-settings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: 安裝依賴套件
        run: pip install openai requests feedparser

      - name: 執行每日新聞生成腳本
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python3 generate_news.py

      - name: Commit 並推送更新內容
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add content.txt last_image_id.txt img/content/ || true
          git commit -m "每日自動更新新聞與圖片 $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit before pull"

          git pull origin main --rebase || echo "Pull failed, continuing with local changes"

          git add content.txt last_image_id.txt img/content/
          git commit -m "每日自動更新新聞與圖片 $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"

          git push
